/**
 * SPDX-License-Identifier: GPL-2.0-only
 * Copyright (C) 2026 Bardia Moshiri <bardia@furilabs.com>
 */

#include "backends/mtk/speech/mtk-speech-protocol.h"

#define CASE_NAME(id) case id: return &#id[8]

const gchar *
mtk_speech_message_name(guint16 msg_id)
{
    switch (msg_id) {
    CASE_NAME(MTK_MSG_A2M_SPH_DL_DIGIT_VOLUME);
    CASE_NAME(MTK_MSG_A2M_SPH_UL_DIGIT_VOLUME);
    CASE_NAME(MTK_MSG_A2M_MUTE_SPH_UL);
    CASE_NAME(MTK_MSG_A2M_MUTE_SPH_DL);
    CASE_NAME(MTK_MSG_A2M_SPH_ON);
    CASE_NAME(MTK_MSG_A2M_SPH_OFF);
    CASE_NAME(MTK_MSG_A2M_SPH_DEV_CHANGE);
    CASE_NAME(MTK_MSG_A2M_PNW_ON);
    CASE_NAME(MTK_MSG_A2M_PNW_OFF);
    CASE_NAME(MTK_MSG_A2M_VM_REC_ON);
    CASE_NAME(MTK_MSG_A2M_VM_REC_OFF);
    CASE_NAME(MTK_MSG_A2M_RECORD_RAW_PCM_ON);
    CASE_NAME(MTK_MSG_A2M_RECORD_RAW_PCM_OFF);
    CASE_NAME(MTK_MSG_A2M_VOIP_RX_ON);
    CASE_NAME(MTK_MSG_A2M_VOIP_RX_OFF);
    CASE_NAME(MTK_MSG_A2M_BGSND_ON);
    CASE_NAME(MTK_MSG_A2M_BGSND_OFF);
    CASE_NAME(MTK_MSG_A2M_BGSND_CONFIG);
    CASE_NAME(MTK_MSG_A2M_VOIP_RX_CONFIG);
    CASE_NAME(MTK_MSG_A2M_TELEPHONY_TX_ON);
    CASE_NAME(MTK_MSG_A2M_TELEPHONY_TX_OFF);
    CASE_NAME(MTK_MSG_A2M_TELEPHONY_TX_CONFIG);
    CASE_NAME(MTK_MSG_A2M_PNW_DL_DATA_NOTIFY);
    CASE_NAME(MTK_MSG_A2M_BGSND_DATA_NOTIFY);
    CASE_NAME(MTK_MSG_A2M_VOIP_RX_DL_DATA_NOTIFY);
    CASE_NAME(MTK_MSG_A2M_VOIP_RX_UL_DATA_NOTIFY);
    CASE_NAME(MTK_MSG_A2M_TELEPHONY_TX_UL_DATA_NOTIFY);
    CASE_NAME(MTK_MSG_A2M_PNW_UL_DATA_READ_ACK);
    CASE_NAME(MTK_MSG_A2M_VM_REC_DATA_READ_ACK);
    CASE_NAME(MTK_MSG_A2M_RAW_PCM_REC_DATA_READ_ACK);
    CASE_NAME(MTK_MSG_A2M_NETWORK_STATUS_ACK);
    CASE_NAME(MTK_MSG_A2M_EPOF_ACK);
    CASE_NAME(MTK_MSG_A2M_DYNAMIC_PAR_IN_STRUCT_SHM);
    CASE_NAME(MTK_MSG_A2M_NW_CODEC_INFO_READ_ACK);
    CASE_NAME(MTK_MSG_A2M_MD_ALIVE_ACK_BACK);
    CASE_NAME(MTK_MSG_A2M_IVS_SWITCH);
    CASE_NAME(MTK_MSG_A2M_PSAP_SWITCH);
    CASE_NAME(MTK_MSG_A2M_IVS_SEND);
    CASE_NAME(MTK_MSG_A2M_PSAP_SEND);
    CASE_NAME(MTK_MSG_A2M_ECALL_CTL_SEQ_SWITCH);
    CASE_NAME(MTK_MSG_A2M_ECALL_HANDSHAKE_INFO_READ_ACK);
    CASE_NAME(MTK_MSG_A2M_ECALL_MSD);
    CASE_NAME(MTK_MSG_A2M_ECALL_TX_CTRL_PAR);
    CASE_NAME(MTK_MSG_A2M_ECALL_RX_CTRL_READ_ACK);

    CASE_NAME(MTK_MSG_M2A_MUTE_SPH_UL_ACK);
    CASE_NAME(MTK_MSG_M2A_MUTE_SPH_DL_ACK);
    CASE_NAME(MTK_MSG_M2A_SPH_ON_ACK);
    CASE_NAME(MTK_MSG_M2A_SPH_OFF_ACK);
    CASE_NAME(MTK_MSG_M2A_SPH_DEV_CHANGE_ACK);
    CASE_NAME(MTK_MSG_M2A_PNW_ON_ACK);
    CASE_NAME(MTK_MSG_M2A_PNW_OFF_ACK);
    CASE_NAME(MTK_MSG_M2A_VM_REC_ON_ACK);
    CASE_NAME(MTK_MSG_M2A_VM_REC_OFF_ACK);
    CASE_NAME(MTK_MSG_M2A_RECORD_RAW_PCM_ON_ACK);
    CASE_NAME(MTK_MSG_M2A_RECORD_RAW_PCM_OFF_ACK);
    CASE_NAME(MTK_MSG_M2A_VOIP_RX_ON_ACK);
    CASE_NAME(MTK_MSG_M2A_VOIP_RX_OFF_ACK);
    CASE_NAME(MTK_MSG_M2A_BGSND_ON_ACK);
    CASE_NAME(MTK_MSG_M2A_BGSND_OFF_ACK);
    CASE_NAME(MTK_MSG_M2A_TELEPHONY_TX_ON_ACK);
    CASE_NAME(MTK_MSG_M2A_TELEPHONY_TX_OFF_ACK);
    CASE_NAME(MTK_MSG_M2A_PNW_DL_DATA_REQUEST);
    CASE_NAME(MTK_MSG_M2A_BGSND_DATA_REQUEST);
    CASE_NAME(MTK_MSG_M2A_VOIP_RX_DL_DATA_REQUEST);
    CASE_NAME(MTK_MSG_M2A_VOIP_RX_UL_DATA_REQUEST);
    CASE_NAME(MTK_MSG_M2A_TELEPHONY_TX_UL_DATA_REQUEST);
    CASE_NAME(MTK_MSG_M2A_PNW_UL_DATA_NOTIFY);
    CASE_NAME(MTK_MSG_M2A_VM_REC_DATA_NOTIFY);
    CASE_NAME(MTK_MSG_M2A_RAW_PCM_REC_DATA_NOTIFY);
    CASE_NAME(MTK_MSG_M2A_EM_DATA_REQUEST);
    CASE_NAME(MTK_MSG_M2A_NETWORK_STATUS_NOTIFY);
    CASE_NAME(MTK_MSG_M2A_EPOF_NOTIFY);
    CASE_NAME(MTK_MSG_M2A_DYNAMIC_PAR_IN_STRUCT_SHM_ACK);
    CASE_NAME(MTK_MSG_M2A_NW_CODEC_INFO_NOTIFY);
    CASE_NAME(MTK_MSG_M2A_MD_ALIVE);
    CASE_NAME(MTK_MSG_M2A_IVS_SWITCH_ACK);
    CASE_NAME(MTK_MSG_M2A_PSAP_SWITCH_ACK);
    CASE_NAME(MTK_MSG_M2A_ECALL_CTL_SEQ_SWITCH_ACK);
    CASE_NAME(MTK_MSG_M2A_ECALL_HANDSHAKE_INFO);
    CASE_NAME(MTK_MSG_M2A_ECALL_MSD_ACK);
    CASE_NAME(MTK_MSG_M2A_ECALL_TX_CTRL_PAR_ACK);
    CASE_NAME(MTK_MSG_M2A_ECALL_RX_CTRL_PAR_NOTIFY);
    default:
        return NULL;
    }
}

#undef CASE_NAME

gboolean
mtk_speech_message_needs_ack(guint16 msg_id)
{
    switch (msg_id) {
    case MTK_MSG_A2M_MUTE_SPH_UL:
    case MTK_MSG_A2M_MUTE_SPH_DL:
    case MTK_MSG_A2M_SPH_ON:
    case MTK_MSG_A2M_SPH_OFF:
    case MTK_MSG_A2M_SPH_DEV_CHANGE:
    case MTK_MSG_A2M_PNW_ON:
    case MTK_MSG_A2M_PNW_OFF:
    case MTK_MSG_A2M_VM_REC_ON:
    case MTK_MSG_A2M_VM_REC_OFF:
    case MTK_MSG_A2M_RECORD_RAW_PCM_ON:
    case MTK_MSG_A2M_RECORD_RAW_PCM_OFF:
    case MTK_MSG_A2M_BGSND_ON:
    case MTK_MSG_A2M_BGSND_OFF:
    case MTK_MSG_A2M_DYNAMIC_PAR_IN_STRUCT_SHM:
    case MTK_MSG_A2M_VOIP_RX_ON:
    case MTK_MSG_A2M_VOIP_RX_OFF:
    case MTK_MSG_A2M_TELEPHONY_TX_ON:
    case MTK_MSG_A2M_TELEPHONY_TX_OFF:
    case MTK_MSG_A2M_IVS_SWITCH:
    case MTK_MSG_A2M_PSAP_SWITCH:
    case MTK_MSG_A2M_ECALL_CTL_SEQ_SWITCH:
    case MTK_MSG_A2M_ECALL_MSD:
    case MTK_MSG_A2M_ECALL_TX_CTRL_PAR:
        return TRUE;
    default:
        return FALSE;
    }
}

guint16
mtk_speech_message_expected_ack(guint16 msg_id)
{
    if (!mtk_speech_message_needs_ack(msg_id))
        return 0;
    return (guint16)(0x8000U | msg_id);
}
